---
title: "Crime Data Analysis"
output: html_document
---
---
title: "EAP_6111_O13_Project-Crime_Data-Analysis"
author: "Tanaya Kavathekar, Madhuri Yadav"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 4.5
    fig_width: 7
    highlight: tango
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_float: true
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = F)
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(include = F)
knitr::opts_chunk$set(warning = F)
```

```{r basicfcn, include=F}
# can add quietly=T option to the require() function
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }


# This function calculates number of columns with type integer or double
count_numeric_columns = function(df) { numericc <- 0
doublec <- 0
for (col in colnames(df)){
  # check type integer
  if (typeof(df[,col]) == "integer"){
    numericc = numericc + 1
  }
  # check type double
  else {
    doublec = doublec + 1
  }
}
# create list of the return variables
  type_list <- list("num" = numericc, "dbl" = doublec) 
  return(type_list)
}
```

```{r load libraries, echo=FALSE}
# Load libraries
loadPkg("plyr")
loadPkg("dplyr")
loadPkg("ggplot2")
loadPkg("data.table")
loadPkg("corrplot")
```

```{r TypeOfCrimeAgainstWomen, include=TRUE}
CrimeAgainstWomen = read.csv("../Data/42_Cases_under_crime_against_women.csv")
# str(CrimeAgainstWomen)
# head(CrimeAgainstWomen)
# nrow(CrimeAgainstWomen)

names(CrimeAgainstWomen)[names(CrimeAgainstWomen) == "ï..Area_Name"] <- "Area_Name"
cnames<- c("Area_Name","Year","Group_Name", "Cases_Reported")
ReqColCAW <- CrimeAgainstWomen[cnames]
  
str(ReqColCAW)
head(ReqColCAW)
nrow(ReqColCAW)

#ReqColCAW %>% group_by(Year,Group_Name) %>% summarise_each(summarize(total = sum(Cases_Reported))

#summarize (group_by(), total_crimes= sum(Cases_Reported))

library(dplyr)

GroupedReqColCAW  <-ReqColCAW %>%  group_by(Year,Group_Name) %>%  summarise(TotalCrimesReported=sum(Cases_Reported))

str(GroupedReqColCAW)
head(GroupedReqColCAW)

anova_type <- aov(TotalCrimesReported ~ Group_Name, data = GroupedReqColCAW)

anova_type
summary(anova_type)
```
```{r litreracy, include=TRUE}

library(data.table)

LitPop = read.csv("../Data/For_Literacy_Population.csv")
LitPop <- na.omit(LitPop)
names(LitPop)[1:6]<- c('Area_Name','Workers','Population','Literate','Illiterate','Crimes')

corr<- cor(as.matrix(LitPop[c('Workers','Population','Literate','Illiterate','Crimes')]), method = "pearson")

corrplot.mixed(corr,lower.col="black", number.cex = 0.7)




```

```{r Region, include=TRUE}
states = read.csv("../Data/01_District_wise_crimes_committed_IPC_2001_2012.csv")
str(states)
head(states)
cnames1<- c("STATE.UT","YEAR","TOTAL.IPC.CRIMES")
ReqColStates <- states[cnames1]
names(ReqColStates)[names(ReqColStates) == "STATE.UT"] <- "Area_Name"
names(ReqColStates)[names(ReqColStates) == "YEAR"] <- "Year"
names(ReqColStates)[names(ReqColStates) == "TOTAL.IPC.CRIMES"] <- "TotalCrimes"

str(ReqColStates)
head(ReqColStates)

anova_Region <- aov(TotalCrimes ~ Area_Name, data = ReqColStates)

anova_type
summary(anova_Region)

```

